<a href="https://colab.research.google.com/github/Li0741/MAT421-SP23/blob/main/ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1 Introduction**

Basic of linear algebra:
---

Sets - Collection of objects {}

Union - A U B - Set containing all elements of A and B

Intersect - A n B - Set Containing all elements thats belong to both A and B

Naturals - N = {1,2,3,4,..}

Wholes - W = N U {0}

Integers - Z = W U {-1,-2,-3,....}

Rationals - Q = { p/g : p ∊ Z , q ∊ Z \ {0}}

Irrationals - I = set of real numbers not expressible as a fraction of integers

Reals - R = Q U I

Complex Numbers - C = {a + bi: a, b ∊ R, i = sqrt(-1) }

In [11]:
#This gives a example of vector in python.
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],
              [2], 
              [3], 
              [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


**1.2 Elements of Linear Algebra**

A linear subspace of V is a subset U ⊆ V that is closed under vector addition and scalar multiplication. That is for all u1, u2 ∊ U and a ∊ R it holds u1 + u2 and a u1 ∊ u


---


Span - let w1,...,wm ∊ V. The span is denoted span(w1,...,wm) is the set of all linear combos of the w's

Every Span is a Linear Subspace - Let W = span(w1,...,wm). Then W is a linear subspace.


---


Column Space - Let A ∊ R^(nxm) be an nxm matrix with columns a1,...,am ∊ R^n. The column space of A, denoted col(A) is the span of the columns of A.


---


Linear Independence - A list of vectors u1,...,um is linearly independent if none of them can be written as a linear combinations of the others.


---


Dimension Theorem - Let U be a linear subspace of V. Any basis of U has the same number of elements. All bases of U have the same length and same number of elements is dim(U).


**Orthonormal Bases**

A list of vectors {u1,...,um} is orthonormal if the u's are pairwise orthogonal and each has a norm 1 .

Orthogonal Projection - Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm. The orthogonal porjection of v ∊ V on U is Pu v = sum(j=1)< v , qj > qj.


---


Best Approximation Theorem - Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm let v ∊ V. For any u ∊ U. ||v-Pu v|| <= ||v-u||.

Pythagorean Theorem - Let u1 v ∊ V be orthogonal. Then ||u + v||^2 = ||u||^2 + ||v||^2



---


Eigenvalues and Eigenvectors - Let A ∊ R^(dxd) be a square matrix. Then 𝜆 ∊ R is an eigenvalue of A if there exists a non-zero vector x != 0 such that Ax = 𝜆x. Vector x is an eigenvector.

Diagonal and Similar Matrices - Let A be similar to a matrix D = diag(𝜆1,...,𝜆d) with distinct diagonal entries, that exists a non-singular matric A such that A = PDP^-1

If A is symmetric, then any 2 eigenvectors from different eigenspaces are orthogonal.



---
The Spectral Theorem of Symmetric Matrices - an n × n
symmetric matrix A has the following properties:
*   A has n real eigenvalues, counting multiplicities.
*   If λ is an eigenvalues of A with multiplicity k, then the eigenspace for λ is k-dimensional.
*   The eigenspaces are mutually orthogonal, in the sense that eigenvectors corresponding to different eigenvalues are orthogonal.
*   A is orthogonally diagonalizable


Compute the eigenvalues and eigenvectors for matrix A = [[2. 2. 4.], [2. 3. 5.], [2. 3. 4]]

In [10]:
import numpy as np
from numpy.linalg import eig

a = np.array([[2, 2, 4], 
        [2, 3, 5],
        [2, 3, 4]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 9.0858344   0.42821417 -0.51404856]
E-vector [[-0.50657506 -0.88978956 -0.52057232]
 [-0.64059399  0.43714525 -0.58654536]
 [-0.57707976  0.13106703  0.6204587 ]]


**1.3 Linear Regression**

QR Decomposition is a preferred iterative method to find all the eigenvalues of a matrix (but not the eigenvectors at the same time). 

Use the qr function in numpy.linalg to decompose matrix A=[[02], [23]]

In [9]:
import numpy as np
from numpy.linalg import qr

a = np.array([[0, 2], 
        [2, 3]])

q, r = qr(a)

print('Q:', q)
print('R:', r)

b = np.dot(q, r)
print('QR:', b)

a = np.array([[0, 2], 
        [2, 3]])
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]]
Iteration 1:
[[3. 2.]
 [2. 0.]]
Iteration 5:
[[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Iteration 10:
[[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Iteration 20:
[[ 4.00000000e+00  9.09484250e-12]
 [ 9.09494702e-12 -1.00000000e+00]]
